<?php
class model_m_produksi_kebun extends Model
{
    function __construct(){
        parent::__construct();
        $this->load->database();
    }
    
    function LoadData($bulan,$tahun){
        $limit = htmlentities($this->input->post('rows'),ENT_QUOTES,'UTF-8');
        $page = htmlentities($this->input->post('page'),ENT_QUOTES,'UTF-8');
        $sidx = htmlentities($this->input->post('sidx'),ENT_QUOTES,'UTF-8');
        $sord = htmlentities($this->input->post('sord'),ENT_QUOTES,'UTF-8');

        $bulan=$this->db->escape_str($bulan);
        $tahun=$this->db->escape_str($tahun);
		$periode =  $tahun."-". $bulan;    
        
		//dummy
		$queries = "SELECT PRODUKSI_KEBUN.COMPANY_CODE,  PRODUKSI_KEBUN.AFDELING, PRODUKSI_KEBUN.PRODUKSI_TM, PRODUKSI_KEBUN.PRODUKSI_TBM, PRODUKSI_KEBUN.dateacct 
FROM (
	SELECT COMPANY.COMPANY_CODE, 'INTI' AS AFDELING, 'INTI' AS TIPE_BLOK, COALESCE(PROD_INTI.PRODUKSI_TM,0) AS PRODUKSI_TM, COALESCE(PROD_INTI.PRODUKSI_TBM, 0) AS PRODUKSI_TBM, '".$periode."-01"."' AS dateacct
	FROM m_company COMPANY
	LEFT JOIN (
			SELECT INTI.COMPANY_CODE, INTI.AFDELING, INTI.TIPE_BLOK, SUM(INTI.PRODUKSI_TM) AS PRODUKSI_TM, SUM(INTI.PRODUKSI_TBM) AS PRODUKSI_TBM, INTI.dateacct
			FROM
			(
				SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, SUM(HASIL_KERJA) AS PRODUKSI_TM, 0 AS PRODUKSI_TBM, dateacct FROM (
					SELECT COMPANY_CODE, 
					CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
					HASIL_KERJA,
					CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
					CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
					CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
					FROM p_progress p
					WHERE p.TGL_PROGRESS BETWEEN '20150626' AND '20150731' 
					-- DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '".$periode."'  
					AND p.ACTIVITY_CODE ='8601003'  
				) INTI_TM
				WHERE INTI_TM.TIPE_TAHUN = 'TM' AND INTI_TM.AFDELING = 'INTI'
				GROUP BY INTI_TM.COMPANY_CODE, INTI_TM.AFDELING
				UNION ALL
				SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, 0 AS PRODUKSI_TM, SUM(HASIL_KERJA) AS PRODUKSI_TBM, dateacct FROM (
					SELECT COMPANY_CODE, 
					CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
					HASIL_KERJA,
					CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
					CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
					CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
					FROM p_progress p
					WHERE -- DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '".$periode."' 
					p.TGL_PROGRESS BETWEEN '20150626' AND '20150731' AND p.ACTIVITY_CODE ='8601003'  
				) INTI_TBM
				WHERE INTI_TBM.TIPE_TAHUN = 'TBM' AND INTI_TBM.AFDELING = 'INTI'
				GROUP BY INTI_TBM.COMPANY_CODE, INTI_TBM.AFDELING
			) INTI
			GROUP BY INTI.COMPANY_CODE, INTI.AFDELING
	) PROD_INTI ON COMPANY.COMPANY_CODE = PROD_INTI.COMPANY_CODE
	WHERE COMPANY.sta_alokasi = 1	
	UNION ALL
	SELECT PLASMA.COMPANY_CODE, PLASMA.AFDELING, PLASMA.TIPE_BLOK, SUM(PLASMA.PRODUKSI_TM) AS PRODUKSI_TM, SUM(PLASMA.PRODUKSI_TBM) AS PRODUKSI_TBM, PLASMA.dateacct
	FROM
	(
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, SUM(HASIL_KERJA) AS PRODUKSI_TM, 0 AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE -- DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '".$periode."' 
			p.TGL_PROGRESS BETWEEN '20150626' AND '20150731' AND p.ACTIVITY_CODE ='8601003'  
		) PLASMA_TM
		WHERE PLASMA_TM.TIPE_TAHUN = 'TM' AND PLASMA_TM.AFDELING <> 'INTI'
		GROUP BY PLASMA_TM.COMPANY_CODE, PLASMA_TM.AFDELING
		UNION ALL
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, 0 AS PRODUKSI_TM, SUM(HASIL_KERJA) AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE -- DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '".$periode."' 
			p.TGL_PROGRESS BETWEEN '20150626' AND '20150731' AND p.ACTIVITY_CODE ='8601003'  
		) PLASMA_TBM
		WHERE PLASMA_TBM.TIPE_TAHUN = 'TBM' AND PLASMA_TBM.AFDELING <> 'INTI'
		GROUP BY PLASMA_TBM.COMPANY_CODE, PLASMA_TBM.AFDELING
	) PLASMA
	GROUP BY PLASMA.COMPANY_CODE, PLASMA.AFDELING
) PRODUKSI_KEBUN
WHERE PRODUKSI_KEBUN.COMPANY_CODE<>''
-- ORDER BY PRODUKSI_KEBUN.COMPANY_CODE, PRODUKSI_KEBUN.TIPE_BLOK
";

        $sql2 = $queries;
       
        if(!$sidx) $sidx =1;
        $query = $this->db->query($sql2);
        $count = $query->num_rows(); 

        if( $count >0 ) {
            $total_pages = @(ceil($count/$limit));
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
            
        $start = $limit * $page - $limit;
        if ($start > 0 ){
            $start = $start;
        } else {
            $start = 0;
        }
        
        //$sql = $queries;
        $sql = $queries." ORDER BY ".$sidx." ".$sord.", PRODUKSI_KEBUN.TIPE_BLOK  LIMIT ".$start.",".$limit." ";
        $objects = $this->db->query($sql,FALSE)->result(); 
        $rows =  array();

        $act = "";
        foreach($objects as $obj)
        {
            $cell = array();
            array_push($cell, htmlentities($obj->COMPANY_CODE,ENT_QUOTES,'UTF-8'));
            array_push($cell, htmlentities($obj->AFDELING,ENT_QUOTES,'UTF-8'));
            array_push($cell, htmlentities($obj->PRODUKSI_TM,ENT_QUOTES,'UTF-8'));
            array_push($cell, htmlentities($obj->PRODUKSI_TBM,ENT_QUOTES,'UTF-8'));
            array_push($cell, htmlentities($obj->dateacct,ENT_QUOTES,'UTF-8'));
            $row = new stdClass();

            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;      

        return $jsonObject;
    }
	
	function LoadDataGKM($bulan,$tahun){
        $limit = htmlentities($this->input->post('rows'),ENT_QUOTES,'UTF-8');
        $page = htmlentities($this->input->post('page'),ENT_QUOTES,'UTF-8');
        $sidx = htmlentities($this->input->post('sidx'),ENT_QUOTES,'UTF-8');
        $sord = htmlentities($this->input->post('sord'),ENT_QUOTES,'UTF-8');

        $bulan=$this->db->escape_str($bulan);
        $tahun=$this->db->escape_str($tahun);
		$periode =  $tahun."-". $bulan;    
        
		//dummy
		$queries = "SELECT PRODUKSI_KEBUN.COMPANY_CODE,  PRODUKSI_KEBUN.AFDELING, PRODUKSI_KEBUN.PRODUKSI_TM, PRODUKSI_KEBUN.PRODUKSI_TBM, PRODUKSI_KEBUN.dateacct 
FROM (
	SELECT INTI.COMPANY_CODE, INTI.AFDELING, INTI.TIPE_BLOK, SUM(INTI.PRODUKSI_TM) AS PRODUKSI_TM, SUM(INTI.PRODUKSI_TBM) AS PRODUKSI_TBM, INTI.dateacct
	FROM
	(
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, SUM(HASIL_KERJA) AS PRODUKSI_TM, 0 AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '".$periode."'  AND p.ACTIVITY_CODE ='8601003'  
		) INTI_TM
		WHERE INTI_TM.TIPE_TAHUN = 'TM' AND INTI_TM.AFDELING = 'INTI'
		GROUP BY INTI_TM.COMPANY_CODE, INTI_TM.AFDELING
		UNION ALL
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, 0 AS PRODUKSI_TM, SUM(HASIL_KERJA) AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '".$periode."' AND p.ACTIVITY_CODE ='8601003'  
		) INTI_TBM
		WHERE INTI_TBM.TIPE_TAHUN = 'TBM' AND INTI_TBM.AFDELING = 'INTI'
		GROUP BY INTI_TBM.COMPANY_CODE, INTI_TBM.AFDELING
	) INTI
	GROUP BY INTI.COMPANY_CODE, INTI.AFDELING
	UNION ALL
	SELECT PLASMA.COMPANY_CODE, PLASMA.AFDELING, PLASMA.TIPE_BLOK, SUM(PLASMA.PRODUKSI_TM) AS PRODUKSI_TM, SUM(PLASMA.PRODUKSI_TBM) AS PRODUKSI_TBM, PLASMA.dateacct
	FROM
	(
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, SUM(HASIL_KERJA) AS PRODUKSI_TM, 0 AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '".$periode."' AND p.ACTIVITY_CODE ='8601003'  
		) PLASMA_TM
		WHERE PLASMA_TM.TIPE_TAHUN = 'TM' AND PLASMA_TM.AFDELING <> 'INTI'
		GROUP BY PLASMA_TM.COMPANY_CODE, PLASMA_TM.AFDELING
		UNION ALL
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, 0 AS PRODUKSI_TM, SUM(HASIL_KERJA) AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '".$periode."' AND p.ACTIVITY_CODE ='8601003'  
		) PLASMA_TBM
		WHERE PLASMA_TBM.TIPE_TAHUN = 'TBM' AND PLASMA_TBM.AFDELING <> 'INTI'
		GROUP BY PLASMA_TBM.COMPANY_CODE, PLASMA_TBM.AFDELING
	) PLASMA
	GROUP BY PLASMA.COMPANY_CODE, PLASMA.AFDELING
) PRODUKSI_KEBUN
WHERE PRODUKSI_KEBUN.COMPANY_CODE<>''
ORDER BY PRODUKSI_KEBUN.COMPANY_CODE, PRODUKSI_KEBUN.TIPE_BLOK";

        $sql2 = $queries;
       	$dbgkm = $this->load->database('lhm_gkm', TRUE); 
        if(!$sidx) $sidx =1;
        $query = $dbgkm->query($sql2);
        $count = $query->num_rows(); 

        if( $count >0 ) {
            $total_pages = @(ceil($count/$limit));
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
            
        $start = $limit * $page - $limit;
        if ($start > 0 ){
            $start = $start;
        } else {
            $start = 0;
        }
        
        $sql = $queries;
        
        $objects = $dbgkm->query($sql,FALSE)->result(); 
        $rows =  array();

        $act = "";
        foreach($objects as $obj)
        {
            $cell = array();
            array_push($cell, htmlentities($obj->COMPANY_CODE,ENT_QUOTES,'UTF-8'));
            array_push($cell, htmlentities($obj->AFDELING,ENT_QUOTES,'UTF-8'));
            array_push($cell, htmlentities($obj->PRODUKSI_TM,ENT_QUOTES,'UTF-8'));
            array_push($cell, htmlentities($obj->PRODUKSI_TBM,ENT_QUOTES,'UTF-8'));
            array_push($cell, htmlentities($obj->dateacct,ENT_QUOTES,'UTF-8'));
            $row = new stdClass();

            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;      

        return $jsonObject;
    }
	
	function LoadData_Adem($bulan,$tahun){
        $limit = htmlentities($this->input->post('rows'),ENT_QUOTES,'UTF-8');
        $page = htmlentities($this->input->post('page'),ENT_QUOTES,'UTF-8');
        $sidx = htmlentities($this->input->post('sidx'),ENT_QUOTES,'UTF-8');
        $sord = htmlentities($this->input->post('sord'),ENT_QUOTES,'UTF-8');

        $bulan=$this->db->escape_str($bulan);
        $tahun=$this->db->escape_str($tahun);
        $periode =  $tahun."-". $bulan;  

        
		$queries = "SELECT * FROM z_produksi_kebun WHERE TO_CHAR(dateacct,'yyyy-mm') = '". $periode. "' order by ad_org_id, afdeling";

        $sql2 = $queries;
		
		$db_adem = $this->load->database('adem', TRUE);
		//var_dump($db_adem->query($sql2));		
       
        if(!$sidx) $sidx =1;
		$query = $db_adem->query($sql2);
        $count = $query->num_rows(); 

        if( $count >0 ) {
            $total_pages = @(ceil($count/$limit));
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
            
        $start = $limit * $page - $limit;
        if ($start > 0 ){
            $start = $start;
        } else {
            $start = 0;
        }
        
        $sql = $queries;
        
        $objects = $db_adem->query($sql,FALSE)->result(); 
        $rows =  array();

        $act = "";
        foreach($objects as $obj)
        {
            $cell = array();
			$company=$this->model_m_produksi_kebun->getCompanyCodeLHM($obj->ad_org_id);
            array_push($cell, htmlentities($company,ENT_QUOTES,'UTF-8'));
            array_push($cell, htmlentities($obj->afdeling,ENT_QUOTES,'UTF-8'));
			array_push($cell, htmlentities($obj->c_bpartner_id,ENT_QUOTES,'UTF-8'));
            array_push($cell, htmlentities($obj->produksi_tm,ENT_QUOTES,'UTF-8'));
            array_push($cell, htmlentities($obj->produksi_tbm,ENT_QUOTES,'UTF-8'));
            array_push($cell, htmlentities($obj->dateacct,ENT_QUOTES,'UTF-8'));
            $row = new stdClass();

            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;      

        return $jsonObject;
    }
    	
	function get_produksi_kebun($periode){
		$periode = $this->db->escape_str($periode);
		$temp_result [] = null;

		$queries = "SELECT PRODUKSI_KEBUN.COMPANY_CODE,  PRODUKSI_KEBUN.AFDELING, PRODUKSI_KEBUN.PRODUKSI_TM, PRODUKSI_KEBUN.PRODUKSI_TBM, PRODUKSI_KEBUN.dateacct 
FROM (
		SELECT COMPANY.COMPANY_CODE, 'INTI' AS AFDELING, 'INTI' AS TIPE_BLOK, COALESCE(PROD_INTI.PRODUKSI_TM,0) AS PRODUKSI_TM, COALESCE(PROD_INTI.PRODUKSI_TBM, 0) AS PRODUKSI_TBM, '".$periode."-01"."' AS dateacct
	FROM m_company COMPANY
	LEFT JOIN (
			SELECT INTI.COMPANY_CODE, INTI.AFDELING, INTI.TIPE_BLOK, SUM(INTI.PRODUKSI_TM) AS PRODUKSI_TM, SUM(INTI.PRODUKSI_TBM) AS PRODUKSI_TBM, INTI.dateacct
			FROM
			(
				SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, SUM(HASIL_KERJA) AS PRODUKSI_TM, 0 AS PRODUKSI_TBM, dateacct FROM (
					SELECT COMPANY_CODE, 
					CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
					HASIL_KERJA,
					CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
					CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
					CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
					FROM p_progress p
					WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003'  
				) INTI_TM
				WHERE INTI_TM.TIPE_TAHUN = 'TM' AND INTI_TM.AFDELING = 'INTI'
				GROUP BY INTI_TM.COMPANY_CODE, INTI_TM.AFDELING
				UNION ALL
				SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, 0 AS PRODUKSI_TM, SUM(HASIL_KERJA) AS PRODUKSI_TBM, dateacct FROM (
					SELECT COMPANY_CODE, 
					CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
					HASIL_KERJA,
					CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
					CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
					CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
					FROM p_progress p
					WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003'  
				) INTI_TBM
				WHERE INTI_TBM.TIPE_TAHUN = 'TBM' AND INTI_TBM.AFDELING = 'INTI'
				GROUP BY INTI_TBM.COMPANY_CODE, INTI_TBM.AFDELING
			) INTI
			GROUP BY INTI.COMPANY_CODE, INTI.AFDELING
	) PROD_INTI ON COMPANY.COMPANY_CODE = PROD_INTI.COMPANY_CODE
	WHERE COMPANY.sta_alokasi = 1		
	UNION ALL
	SELECT PLASMA.COMPANY_CODE, PLASMA.AFDELING, PLASMA.TIPE_BLOK, SUM(PLASMA.PRODUKSI_TM) AS PRODUKSI_TM, SUM(PLASMA.PRODUKSI_TBM) AS PRODUKSI_TBM, PLASMA.dateacct
	FROM
	(
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, SUM(HASIL_KERJA) AS PRODUKSI_TM, 0 AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003'  
		) PLASMA_TM
		WHERE PLASMA_TM.TIPE_TAHUN = 'TM' AND PLASMA_TM.AFDELING <> 'INTI'
		GROUP BY PLASMA_TM.COMPANY_CODE, PLASMA_TM.AFDELING
		UNION ALL
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, 0 AS PRODUKSI_TM, SUM(HASIL_KERJA) AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003'  
		) PLASMA_TBM
		WHERE PLASMA_TBM.TIPE_TAHUN = 'TBM' AND PLASMA_TBM.AFDELING <> 'INTI'
		GROUP BY PLASMA_TBM.COMPANY_CODE, PLASMA_TBM.AFDELING
	) PLASMA
	GROUP BY PLASMA.COMPANY_CODE, PLASMA.AFDELING
) PRODUKSI_KEBUN
WHERE PRODUKSI_KEBUN.COMPANY_CODE<>''
ORDER BY PRODUKSI_KEBUN.COMPANY_CODE, PRODUKSI_KEBUN.TIPE_BLOK";
	
		$this->db->reconnect();	
    	$sQuery = $this->db->query($queries);
    	$numrows = $sQuery->num_rows();		
	
        if ($numrows > 0){
            $temp = $sQuery->row_array();
            $temp_result = array(); 
            foreach ( $sQuery->result_array() as $row ){
                $temp_result [] = $row;                
            }
        }
		
        $this->db->close();
        return $temp_result;
	}
	
	function get_produksi_kebun_percompany($periode, $pt){
		$periode = $this->db->escape_str($periode);
		$temp_result [] = null;

		$queries = "SELECT PRODUKSI_KEBUN.COMPANY_CODE,  PRODUKSI_KEBUN.AFDELING, PRODUKSI_KEBUN.PRODUKSI_TM, PRODUKSI_KEBUN.PRODUKSI_TBM, PRODUKSI_KEBUN.dateacct 
FROM (
		SELECT COMPANY.COMPANY_CODE, 'INTI' AS AFDELING, 'INTI' AS TIPE_BLOK, COALESCE(PROD_INTI.PRODUKSI_TM,0) AS PRODUKSI_TM, COALESCE(PROD_INTI.PRODUKSI_TBM, 0) AS PRODUKSI_TBM, '".$periode."-01"."' AS dateacct
	FROM m_company COMPANY
	LEFT JOIN (
			SELECT INTI.COMPANY_CODE, INTI.AFDELING, INTI.TIPE_BLOK, SUM(INTI.PRODUKSI_TM) AS PRODUKSI_TM, SUM(INTI.PRODUKSI_TBM) AS PRODUKSI_TBM, INTI.dateacct
			FROM
			(
				SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, SUM(HASIL_KERJA) AS PRODUKSI_TM, 0 AS PRODUKSI_TBM, dateacct FROM (
					SELECT COMPANY_CODE, 
					CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
					HASIL_KERJA,
					CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
					CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
					CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
					FROM p_progress p
					WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003' AND company_code = '". $pt. "'	  
				) INTI_TM
				WHERE INTI_TM.TIPE_TAHUN = 'TM' AND INTI_TM.AFDELING = 'INTI'
				GROUP BY INTI_TM.COMPANY_CODE, INTI_TM.AFDELING
				UNION ALL
				SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, 0 AS PRODUKSI_TM, SUM(HASIL_KERJA) AS PRODUKSI_TBM, dateacct FROM (
					SELECT COMPANY_CODE, 
					CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
					HASIL_KERJA,
					CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
					CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
					CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
					FROM p_progress p
					WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003' AND company_code = '". $pt. "'  
				) INTI_TBM
				WHERE INTI_TBM.TIPE_TAHUN = 'TBM' AND INTI_TBM.AFDELING = 'INTI'
				GROUP BY INTI_TBM.COMPANY_CODE, INTI_TBM.AFDELING
			) INTI
			GROUP BY INTI.COMPANY_CODE, INTI.AFDELING
	) PROD_INTI ON COMPANY.COMPANY_CODE = PROD_INTI.COMPANY_CODE
	WHERE COMPANY.sta_alokasi = 1 AND COMPANY.company_code = '". $pt. "'		
	UNION ALL
	SELECT PLASMA.COMPANY_CODE, PLASMA.AFDELING, PLASMA.TIPE_BLOK, SUM(PLASMA.PRODUKSI_TM) AS PRODUKSI_TM, SUM(PLASMA.PRODUKSI_TBM) AS PRODUKSI_TBM, PLASMA.dateacct
	FROM
	(
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, SUM(HASIL_KERJA) AS PRODUKSI_TM, 0 AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003' AND company_code = '". $pt. "'  
		) PLASMA_TM
		WHERE PLASMA_TM.TIPE_TAHUN = 'TM' AND PLASMA_TM.AFDELING <> 'INTI'
		GROUP BY PLASMA_TM.COMPANY_CODE, PLASMA_TM.AFDELING
		UNION ALL
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, 0 AS PRODUKSI_TM, SUM(HASIL_KERJA) AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003' AND company_code = '". $pt. "'  
		) PLASMA_TBM
		WHERE PLASMA_TBM.TIPE_TAHUN = 'TBM' AND PLASMA_TBM.AFDELING <> 'INTI'
		GROUP BY PLASMA_TBM.COMPANY_CODE, PLASMA_TBM.AFDELING
	) PLASMA
	GROUP BY PLASMA.COMPANY_CODE, PLASMA.AFDELING
) PRODUKSI_KEBUN
WHERE PRODUKSI_KEBUN.COMPANY_CODE<>''
ORDER BY PRODUKSI_KEBUN.COMPANY_CODE, PRODUKSI_KEBUN.TIPE_BLOK";
		//var_dump($queries);	
		$this->db->reconnect();	
    	$sQuery = $this->db->query($queries);
    	$numrows = $sQuery->num_rows();		
	
        if ($numrows > 0){
            $temp = $sQuery->row_array();
            $temp_result = array(); 
            foreach ( $sQuery->result_array() as $row ){
                $temp_result [] = $row;                
            }
        }
		
        $this->db->close();
        return $temp_result;
	}
	    	
	function get_produksi_kebun_gkm($periode){
		$periode = $this->db->escape_str($periode);
		$temp_result [] = null;

		$queries = "SELECT PRODUKSI_KEBUN.COMPANY_CODE,  PRODUKSI_KEBUN.AFDELING, PRODUKSI_KEBUN.PRODUKSI_TM, PRODUKSI_KEBUN.PRODUKSI_TBM, PRODUKSI_KEBUN.dateacct 
FROM (
	SELECT INTI.COMPANY_CODE, INTI.AFDELING, INTI.TIPE_BLOK, SUM(INTI.PRODUKSI_TM) AS PRODUKSI_TM, SUM(INTI.PRODUKSI_TBM) AS PRODUKSI_TBM, INTI.dateacct
	FROM
	(
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, SUM(HASIL_KERJA) AS PRODUKSI_TM, 0 AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003'  
		) INTI_TM
		WHERE INTI_TM.TIPE_TAHUN = 'TM' AND INTI_TM.AFDELING = 'INTI'
		GROUP BY INTI_TM.COMPANY_CODE, INTI_TM.AFDELING
		UNION ALL
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, 0 AS PRODUKSI_TM, SUM(HASIL_KERJA) AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003'  
		) INTI_TBM
		WHERE INTI_TBM.TIPE_TAHUN = 'TBM' AND INTI_TBM.AFDELING = 'INTI'
		GROUP BY INTI_TBM.COMPANY_CODE, INTI_TBM.AFDELING
	) INTI
	GROUP BY INTI.COMPANY_CODE, INTI.AFDELING
	UNION ALL
	SELECT PLASMA.COMPANY_CODE, PLASMA.AFDELING, PLASMA.TIPE_BLOK, SUM(PLASMA.PRODUKSI_TM) AS PRODUKSI_TM, SUM(PLASMA.PRODUKSI_TBM) AS PRODUKSI_TBM, PLASMA.dateacct
	FROM
	(
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, SUM(HASIL_KERJA) AS PRODUKSI_TM, 0 AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003'  
		) PLASMA_TM
		WHERE PLASMA_TM.TIPE_TAHUN = 'TM' AND PLASMA_TM.AFDELING <> 'INTI'
		GROUP BY PLASMA_TM.COMPANY_CODE, PLASMA_TM.AFDELING
		UNION ALL
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, 0 AS PRODUKSI_TM, SUM(HASIL_KERJA) AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003'  
		) PLASMA_TBM
		WHERE PLASMA_TBM.TIPE_TAHUN = 'TBM' AND PLASMA_TBM.AFDELING <> 'INTI'
		GROUP BY PLASMA_TBM.COMPANY_CODE, PLASMA_TBM.AFDELING
	) PLASMA
	GROUP BY PLASMA.COMPANY_CODE, PLASMA.AFDELING
) PRODUKSI_KEBUN
WHERE PRODUKSI_KEBUN.COMPANY_CODE<>''
ORDER BY PRODUKSI_KEBUN.COMPANY_CODE, PRODUKSI_KEBUN.TIPE_BLOK";
	
		$dbgkm = $this->load->database('lhm_gkm', TRUE); 
    	$sQuery = $dbgkm->query($queries);
    	$numrows = $sQuery->num_rows();		
	
        if ($numrows > 0){
            $temp = $sQuery->row_array();
            $temp_result = array(); 
            foreach ( $sQuery->result_array() as $row ){
                $temp_result [] = $row;                
            }
        }
		
        $dbgkm->close();
        return $temp_result;
	}
	
	function get_produksi_kebun_percompany_gkm($periode, $pt){
		$periode = $this->db->escape_str($periode);
		$temp_result [] = null;

		$queries = "SELECT PRODUKSI_KEBUN.COMPANY_CODE,  PRODUKSI_KEBUN.AFDELING, PRODUKSI_KEBUN.PRODUKSI_TM, PRODUKSI_KEBUN.PRODUKSI_TBM, PRODUKSI_KEBUN.dateacct 
FROM (
	SELECT INTI.COMPANY_CODE, INTI.AFDELING, INTI.TIPE_BLOK, SUM(INTI.PRODUKSI_TM) AS PRODUKSI_TM, SUM(INTI.PRODUKSI_TBM) AS PRODUKSI_TBM, INTI.dateacct
	FROM
	(
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, SUM(HASIL_KERJA) AS PRODUKSI_TM, 0 AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003'  AND company_code = '". $pt. "'
		) INTI_TM
		WHERE INTI_TM.TIPE_TAHUN = 'TM' AND INTI_TM.AFDELING = 'INTI'
		GROUP BY INTI_TM.COMPANY_CODE, INTI_TM.AFDELING
		UNION ALL
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, 0 AS PRODUKSI_TM, SUM(HASIL_KERJA) AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003' AND company_code = '". $pt. "'  
		) INTI_TBM
		WHERE INTI_TBM.TIPE_TAHUN = 'TBM' AND INTI_TBM.AFDELING = 'INTI'
		GROUP BY INTI_TBM.COMPANY_CODE, INTI_TBM.AFDELING
	) INTI
	GROUP BY INTI.COMPANY_CODE, INTI.AFDELING
	UNION ALL
	SELECT PLASMA.COMPANY_CODE, PLASMA.AFDELING, PLASMA.TIPE_BLOK, SUM(PLASMA.PRODUKSI_TM) AS PRODUKSI_TM, SUM(PLASMA.PRODUKSI_TBM) AS PRODUKSI_TBM, PLASMA.dateacct
	FROM
	(
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, SUM(HASIL_KERJA) AS PRODUKSI_TM, 0 AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003' AND company_code = '". $pt. "'  
		) PLASMA_TM
		WHERE PLASMA_TM.TIPE_TAHUN = 'TM' AND PLASMA_TM.AFDELING <> 'INTI'
		GROUP BY PLASMA_TM.COMPANY_CODE, PLASMA_TM.AFDELING
		UNION ALL
		SELECT COMPANY_CODE, AFDELING, TIPE_BLOK, 0 AS PRODUKSI_TM, SUM(HASIL_KERJA) AS PRODUKSI_TBM, dateacct FROM (
			SELECT COMPANY_CODE, 
			CASE WHEN (CASE WHEN (SUBSTRING(LOCATION_CODE,6,1) = '8') OR (SUBSTRING(LOCATION_CODE,6,1) = '9')  THEN YEAR(now())-CAST(CONCAT('19',RIGHT(LOCATION_CODE,2)) AS UNSIGNED) ELSE YEAR(now())-CAST(CONCAT('20',RIGHT(LOCATION_CODE,2))AS UNSIGNED) END) < 4 THEN 'TBM' ELSE 'TM' END AS TIPE_TAHUN,
			HASIL_KERJA,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE 'PLASMA' END AS TIPE_BLOK,
			CASE WHEN (LEFT(LOCATION_CODE,1)='O') THEN 'INTI' ELSE CONCAT(RIGHT(COMPANY_CODE,3),'-AFD-',LEFT(LOCATION_CODE,2)) END AS AFDELING,
			CONCAT(DATE_FORMAT(TGL_PROGRESS, '%Y-%m'),'-01') AS dateacct
			FROM p_progress p
			WHERE DATE_FORMAT(p.TGL_PROGRESS,'%Y-%m') = '". $periode. "' AND p.ACTIVITY_CODE ='8601003'  
		) PLASMA_TBM
		WHERE PLASMA_TBM.TIPE_TAHUN = 'TBM' AND PLASMA_TBM.AFDELING <> 'INTI' AND company_code = '". $pt. "'
		GROUP BY PLASMA_TBM.COMPANY_CODE, PLASMA_TBM.AFDELING
	) PLASMA
	GROUP BY PLASMA.COMPANY_CODE, PLASMA.AFDELING
) PRODUKSI_KEBUN
WHERE PRODUKSI_KEBUN.COMPANY_CODE<>''
ORDER BY PRODUKSI_KEBUN.COMPANY_CODE, PRODUKSI_KEBUN.TIPE_BLOK";
		//var_dump($queries);	
		$dbgkm = $this->load->database('lhm_gkm', TRUE); 
    	$sQuery = $dbgkm->query($queries);
    	$numrows = $sQuery->num_rows();	
		
        if ($numrows > 0){
            $temp = $sQuery->row_array();
            $temp_result = array(); 
            foreach ( $sQuery->result_array() as $row ){
                $temp_result [] = $row;                
            }
        }
		
        $dbgkm->close();
        return $temp_result;
	}
	
	function get_xls($company, $bulan, $tahun){
		$query="SELECT HA.BLOCKID, HA.HECTPLANTED, HA.NUMPLANTATION, HA.SPH
,rawat.TGL_DETEKSI, rawat.TIPE_produksi_kebun, rawat.PKK_SAMPLE, rawat.PKK_TRS, rawat.TIPE_KATAGORI
FROM (	
	SELECT f.BLOCKID, COALESCE(SUM(f.HECTPLANTED),0) AS HECTPLANTED, COALESCE(SUM(f.NUMPLANTATION),0) AS NUMPLANTATION,
	COALESCE(SUM(COALESCE(f.NUMPLANTATION,0)/COALESCE(f.HECTPLANTED,0)),0) AS SPH
	FROM m_fieldcrop f
	WHERE f.COMPANY_CODE='".$company."'
	GROUP BY f.COMPANY_CODE, f.BLOCKID
) HA
LEFT JOIN (
	SELECT * FROM s_produksi_kebun r 
	WHERE r.COMPANY_CODE = '".$company."' AND r.BULAN = '".$bulan."' AND r.TAHUN = '".$tahun."' AND r.ACTIVE =1
) rawat ON HA.BLOCKID = rawat.BLOK_TANAH";


		$sQuery = $this->db->query($query);
		$numrows = $sQuery->num_rows();
        if ($numrows > 0){
        	$temp = $sQuery->row_array();
            $temp_result = array(); 
            foreach ( $sQuery->result_array() as $row )
            {
                $temp_result [] = $row;
                
            }
		}else{
			$temp_result = NULL;	
		}
		return $temp_result;
	}
	
	function getCompanyIDAdem($company){
		
		if ($company=='TPAI'){
			$company = 'PAI' ;	
		}else{
			$company = 	$company;
		}
		$pgsql = $this->load->database('adem', TRUE);
		$pgquery = "SELECT ad_org_id as ret FROM ad_org WHERE value = '".$company."-Site"."' LIMIT 1";
		$query = $pgsql->query($pgquery);
		
		$data = array_shift($query->result_array());
		$temp = $data['ret'];
		$this->db->close();
		return $temp;
	}
	
	function getCBPatnerAdem($name){
		
		$pgsql = $this->load->database('adem', TRUE);
//		$pgquery = "SELECT ad_org_id as ret FROM ad_org WHERE value = '".$company."-Site"."' LIMIT 1";
		$pgquery = "select c_bpartner_id from c_salesregion where name = '".$name."' LIMIT 1";
		//var_dump($pgquery);
		$query = $pgsql->query($pgquery);
		
		$data = array_shift($query->result_array());
		$temp = $data['c_bpartner_id'];
		$this->db->close();
		return $temp;
	}
	
	function getCompanyCodeLHM($id){
		
		$pgsql = $this->load->database('adem', TRUE);
		$pgquery = "SELECT substring(value,1,3) as ret FROM ad_org WHERE ad_org_id = ".$id." LIMIT 1";
		$query = $pgsql->query($pgquery);
		//var_dump($pgquery);
		$data = array_shift($query->result_array());
		
		if ($data['ret']=='PAI'){
			$temp = 'TPAI' ;	
		}else{
			$temp = $data['ret'];
		}
		$this->db->close();
		return $temp;
	}
	
	function getStatusProsesAdem($company, $periode, $afdeling){
		$value='';
		$sCheckAdem="SELECT processed FROM z_produksi_kebun WHERE ad_org_id = '".$company."' AND dateacct = '".$periode."' AND afdeling ='".$afdeling."'";
		//var_dump("SELECT processed FROM z_produksi_kebun WHERE ad_org_id = '".$company."' AND dateacct = '".$periode."' AND afdeling ='".$afdeling."'");		
		$db_adem = $this->load->database('adem', TRUE);
		$db_adem->reconnect();
		$qsCheckAdem = $db_adem->query($sCheckAdem);
						
		if($qsCheckAdem->num_rows() > 0){
			$row = $qsCheckAdem->row();            
			$value = $row->processed;    
		}
		return $value; 						
	}
}
?>
